### ISSUE TITLE
database schema

### ISSUE THREAD

**Issue by neeksor** [Song-Li/cross_browser#73]
Hello,
Thank you for publishing this software. I setup the fingerprint client and server but ran into an issue when the client attempts to post to /details because of a missing table in the database. Could you provide the schema for the database 'uniquemachine' and it's tables?

**Comment by Song-Li** [comment]
Hello，
This project has many versions (cuz this is a research project and there are so many tests and history versions). Currently the database only has 1 table named "features", it's:
![screen shot 2017-01-16 at 3 22 17 pm](https://cloud.githubusercontent.com/assets/5368897/21997897/c2ff2fae-dbff-11e6-8d5c-3fbd329dc3b7.png)
