### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jnardone** [Song-Li/cross_browser#75]
Have you considered adding an explicit license to this code (e.g. MIT, BSD)?

**Comment by Song-Li** [comment]
Thank you for your suggestion. The license will be MIT. I'll add it later.

**Comment by jnardone** [comment]
So you said MIT here, but the checked-in license is GPL?

**Comment by Song-Li** [comment]
@jnardone I'm sorry. I wanted to use MIT. But after the discussion with professor, we decided to use GPL. So sorry for that.

**Comment by jnardone** [comment]
THanks for the feedback.

**Comment by nebi-frame** [comment]
@Song-Li why did you make it gpl, you're basically destroying commercial usage of this wonderful repo?
