### ISSUE TITLE
Cross browser fingerprinting not working properly.

### ISSUE THREAD

**Issue by AhsanEjazC** [Song-Li/cross_browser#82]
I tried the demo on firefox, edge, chrome, internet explorer and vivaldi on same machine. Chrome and vivaldi are based on webkit, so that may be the reason. Results on edge and firefox are different. Does not work on latest internet explorer version. I am on win 10, gtx 960m gpu.  One thing was that most results were same on gpu side except for 4. And font detection does not work well across all browser. Firefox detects less than chrome.

**Comment by rrfaria** [comment]
I saw the same issue ... I did the same test and all fingerprints are differents .. I also tried the internet explorer 10 and 11 and all new browsers and all are with the same issue.

**Comment by nebi-frame** [comment]
By default it comes with detected language support, you should deselect that one, and remember their contribution is mostly GPU side, no one was able to get great entropy for GPU+os other than these guys.
